import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./vendors.css";
import "./icon.css";
import "./style.css";
import "./globals.css";
import "./responsive.min.css";
import "./demo.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JCI Regatta Iloilo ",
  description: "Generated by create next app",
  icons: "images/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://example.com/styles.css" />
      </Head>
      <body
        data-mobile-nav-trigger-alignment="right"
        data-mobile-nav-style="modern"
        data-mobile-nav-bg-color="#1d1d1d"
      >
        {children}
      </body>
    </html>
  );
}
